const Router = require('express')
const router = new Router()

const projectRouter = require('./projectRouter')
const roleRouter = require('./roleRouter')
const teamRouter = require('./teamRouter')
const testRouter = require('./testRouter')
const userRouter = require('./userRouter')
const professionRouter = require('./professionRouter')
const projectProfessionRouter = require('./projectProfessionRouter')
const projectRequestRouter = require('./projectRequestRouter')
const projectTechnologyRouter = require('./projectTechnologyRouter')
const statusRouter = require('./statusRouter')
const tasChangeRouter = require('./tasChangeRouter')
const tasComentRouter = require('./tasComentRouter')
const tasEstimateRouter = require('./tasEstimateRouter')
const taskRouter = require('./taskRouter')
const technologyRouter = require('./technologyRouter')
const testUserRouter = require('./testUserRouter')

router.use('/project', projectRouter)
router.use('/role', roleRouter)
router.use('/team', teamRouter)
router.use('/test', testRouter)
router.use('/user', userRouter)
router.use('/profession', professionRouter)
router.use('/projectProfession', projectProfessionRouter)
router.use('/projectRequest', projectRequestRouter)
router.use('/projectTechnology', projectTechnologyRouter)
router.use('/status', statusRouter)
router.use('/tasChange', tasChangeRouter)
router.use('/tasComent', tasComentRouter)
router.use('/tasEstimate', tasEstimateRouter)
router.use('/task', taskRouter)
router.use('/technology', technologyRouter)
router.use('/testUser', testUserRouter)


module.exports = router